[package]
name = "nbt"
version = "0.1.0"
authors = ["Purple Myst <PurpleMyst@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.94", features = [ "unstable", "derive" ] }
cesu8 = "1.1.0"

[dev-dependencies]
proptest = "0.9.4"
serde-value = "0.6.0"
